#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 27 17:05:41 2021

@author: admin
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 27 13:15:36 2021

@Judul        : Praktikum 2 Materi
@Nama         : Banon Djinawi Sri Mutiari
@NIM          : 065002100006
@Materi       : Operasi Aritmatika
@Hari/tanggal : 27/09/2021

"""
angka1 = float(input("masukkan angka 1: "))
angka2 = float(input("masukkan angka 2:"))

angka1 = angka1 + angka2
print("hasil angka1 dan angka2 itu adalah? ", angka1)

angka2 = angka1 - angka2
print("selisih angka1 dan angka2 itu adalah? ", angka2)

angka3 = angka1 * angka2
print("perkalian angka1 dan angka2 itu adalah? ", angka3)

angka4 = angka1 / angka2
print("pembagian angka1 dan angka2 itu adalah? ", angka4)

angka5 = angka1 % angka2
print("sisa pembagian angka1 dan angka2 itu adalah? ", angka5)

print("logaritma baris 10 adalah ", angka1)

angka7 = 1 ** 2 
print("angka1 pangkat angka2 =", angka7)
