#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@Materi       : Search, List & Sorting
@Judul        : Praktikum 11 lat.2 (modul 10)
@Hari/Tanggal : Senin, 2 Desember 2021
@author       : Banon Djinawi Sri Mutiari
@NIM          : 065002100006
@Prodi        : Sistem Informasi

"""
class bubbleSort:
	

	def __init__(self, angka):
		self.angka = angka
		self.panjang = len(angka)

	def __str__(self):
		return " ".join([str(x)
						for x in self.angka])

	def bubbleSortRecursive(self, n = None):
		if n is None:
			n = self.panjang

		if n == 1:
			return

		for i in range(n - 1):
			if self.angka[i] > self.angka[i + 1]:
				self.angka[i], self.angka[i + 1] = self.angka[i + 1], self.angka[i]

		self.bubbleSortRecursive(n - 1)

def main():
	angka = [200, 34, 70, 1, 21, 43, 120,(-50)]
	
	
	sort = bubbleSort(angka)
	
	
	sort.bubbleSortRecursive()
	print("dengan sortingan sebagai berikut :\n", sort)


if __name__ == "__main__":
	main()
