#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 18 13:20:14 2021
@Praktikum 5
@Materi       : Algoritma Dan Pemograman
@Judul        : Struktur Kendali
@Hari/Tanggal : Senin, 18 Oktober 2021
@author       : Banon Djinawi Sri Mutiari
@NIM          : 065002100006

"""
skor = 0    
NilaiMurid = list()

ulang = 0
nomor = 0
while ulang == 0:
    nomor += 1
    I = str(input('"selesai" untuk mengakhiri!\nmasukan nilai : ')) 
    if I == 'selesai': 
        ulang = 1
    else: 
        if I == 'A': 
            skor = float(4.00)
        elif I == 'A-':
            skor = float(3.75)
        elif I == 'B+':
            skor = float(3.50)
        elif I == 'B':
            skor = float(3.00)
        elif I == 'B-':
            skor = float(2.75)
        elif I == 'C+':
            skor = float(2.50)
        elif I == 'C':
            skor = float(2.00)
        elif I == 'C-':
            skor = float(1.75)
        elif I == 'D':
            skor = float(1.50)
        elif I == 'E':
            skor = float(1.25)
        else:
            print('Saya tidak mengerti...')
            skor = 0
        print(('\nNilai ke-{0} = {1}').format(nomor,skor))
        NilaiMurid.append(skor)
    
rata2 = sum(NilaiMurid) / len(NilaiMurid)
print('Rata - Rata Nilai Murid Tersebut Adalah :', rata2)
