#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on Sun Nov  7 21:51:38 2021
@Praktikum 7
@Materi       : Function
@Judul        : Praktikum 7 latihan 2
@Hari/Tanggal : minggu , 07 November 2021
@author       : Banon Djinawi Sri Mutiari
@NIM          : 065002100006

"""

def month( Bulan = 0):
    p = True
    while p == True:
        bulan = int(input("Tolong inputkan bulan dari ( 1- 12 ): "))
        if bulan == 1 or bulan == 3 or bulan == 5 or bulan == 7 or bulan == 8 or bulan == 10 or bulan == 12:
            print(" di dalam bulan ini terdapat 31 hari ")
            print(" Enter 0 untuk menghentikan programnya ")
            
        elif bulan == 2:
            year = int(input('Masukkan tahunnya: '))
            if (year % 4 == 0 and bulan == 2):
                print(" di dalam bulan ini terdapat 29 hari ")
                print(" Enter 0 untuk menghentikan programnya ")
                
            else:
                print(" di dalam bulan ini terdapat 28 hari ")
                print(" Enter 0 untuk menghentikan programnya ")
                
        elif bulan == 4 or bulan == 6 or bulan == 9 or bulan == 11:
            print(" di dalam bulan ini terdapat 30 hari ")
            print(" Enter 0 untuk menghentikan programnya ")
            
        elif bulan == 0:
            p = False
            print(" Terima kasih ya karena telah menggunakan program tersebut ")
            
days = month()
