#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@Materi       : File Handling
@Judul        : Praktikum 10 lat.2 (modul 9)
@Hari/Tanggal : Jum'at, 26 November 2021
@author       : Banon Djinawi Sri Mutiari
@NIM          : 065002100006
@Prodi        : Sistem Informasi

"""

print("PROGRAM MEMBUAT FILE")
print("===============================================")

title = str(input("MASUKAN JUDUL FILE:"))
filename = (f"{title}.txt")
f = open(filename, "w")
f.close()
print("===============================================")
print(f"FILE {filename} TELAH DIBUAT!!")
print("TEKAN N atau n untuk menghentikan program")
print("===============================================")

def write(string):
    file = open(f"{title}.txt","w")
    file.write(str(string))
    file.close()

def read ():
    file = open(f"{title}.txt", "r")
    teks = file.read()
    print(teks)

baris = True
while baris == True:
    isi = (input(""))
    if isi == "n" or isi == "N":
        print("\nTEKS TELAH TERSIMPAN")
        baris = False
    else:
        write(isi)
        read()
       
