#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""

@Laporan Praktikum 8
@Materi       : fungsi (Function)
@Judul        : Praktikum 8 latihan 2 (modul 7)
@Hari/Tanggal : Minggu, 14 November 2021
@author       : Banon Djinawi Sri Mutiari
@NIM          : 065002100006

"""

angka = ""

def ordinalNumber(x):
    while angka !=0:
        if (angka == 1):
            return str(angka)+"st"
        if (angka == 2):
            return str(angka)+"nd"
        if (angka == 3):
            return str (angka)+"rd"
        if angka in range(4,21):
            return str(angka)+"th"
        if (angka == 31):
            return str (angka)+"st"
        if (angka == 32):
            return str (angka)+"nd"
        if (angka == 33):
            return str (angka)+"rd"
        else:
            print("error")
    else:
        print("error")
            
angka = int(input("input nomor = "))
print(ordinalNumber(angka))
