#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
@Materi       : Recursive Function
@Judul        : Praktikum 9 lat.2 (modul 8)
@Hari/Tanggal : Kamis, 18 November 2021
@author       : Banon Djinawi Sri Mutiari
@NIM          : 065002100006

"""
p = int(input("Masukkan Angka : "))
q = int(input("Masukkan Angka yang ingin dipangkatkan: "))

def pangkat( p, q ):
    
    if q >= 1 :
        return p * pangkat(p, q  - 1)
    
    return p

hasil = pangkat( p, q )
print(f"hasilnya adalah = {hasil}")
