#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@Materi       : Pengantar Data Science
@Judul        : Laporan Praktikum 13 lat.2 (modul 12)
@Hari/Tanggal : Kamis,23 Desember 2021
@author       : Banon Djinawi Sri Mutiari
@NIM          : 065002100006
@Prodi        : Sistem Informasi

"""
import pandas as pd

def pertama(data):
    
    file = open("negaraMean.csv","w")
    file.write(data)
    file.close()

def kedua(data):
    
    file = open("NegaraStandarDevisiasi.csv","w")
    file.write(data)
    file.close()

data = {"Negara": ["Indonesia", "Jepang", "India", "China", "Amerika Serikat", "Brazil", "Rusia"],
        "Ibu Kota": ["Jakarta", "Tokyo", "New Delhi", "Beijing", "Washington DC", "Brazilia", "Moskow"],
        "Benua": ["Asia", "Asia", "Asia", "Asia", "Amerika", "Amerika", "Asia"],
        "Luas": [1905, 377, 3287, 9597, 9834, 8515, 17098],
        "Populasi": [264, 143, 1252, 1357, 329, 210, 146] }

df = pd.DataFrame(data)
mean = df.groupby(['Benua']).mean()
std = df.groupby(['Benua']).std()

print("Berikut Merupakan Data Framenya :\n")
print(df)
print("\n Berikut Merupakan Data Mean :")
print(mean)
print("\n Berikut Merupakan Data Standar Devisiasi :")
print(std)
pertama(str(mean))
kedua(str(std))
print("\n File Telah Berhasil dibuat")   
