#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""

@Materi       : Recursive Function
@Judul        : Praktikum 9 lat.1 (modul 8)
@Hari/Tanggal : senin, 15 November 2021
@author       : Banon Djinawi Sri Mutiari
@NIM          : 065002100006

"""
def penjumlahan(angka = 0, jmlh = 0, n = 1):
    if (jmlh <= 0):
        return 0
    else:
        angka = int(input("Masukkan bilangan ke-" + str(n) + ": "))
        if(jmlh == 1):
            return angka
        else:
            n+=1
            return angka + penjumlahan(angka, jmlh-1, n)
        
jumlah = int(input("Masukkan jumlahnya: "))  
nilai  = penjumlahan(jmlh = jumlah)
print("Hasil dari penjumlahan tersebut adalah: " + str(nilai))      
                          
